### ISSUE TITLE
Checklist for 1.0.0

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/Madness#1]
- [x] CI for building
- [x] Basic nuget properties like name, description, icon
- [x] First nuget release
- [x] Renovate for package updates
- [x] CI for publishing
- [x] Other parts of `.github` directory
- [x] Proxy methods at least covering ASF usage (so we can reduce amount of `#if`)
- [x] Consider moving static classes to deeper namespaces (e.g. `JustArchiNET.Madness.File`) so they don't automatically pollute file if somebody requires only static extensions available as part of `JustArchiNET.Madness`
- [x] README update
- [ ] Probably more stuff comes up along the way

If you believe I missed anything important, let me know.
